[[https://github.com/HenryS1/bot-match/tree/master][https://github.com/HenryS1/bot-match/actions/workflows/ci.yaml/badge.svg]]

* Bot match

This project provides building blocks for an AI bot match runner. Bot
processes are run in docker containers and managed using the docker
API with http over unix sockets. 

Bot processes are started as the game launches and immediately paused.
At the start of each bot's turn the bot process is resumed and given
its input for the turn. After the allocated turn time the bot process
is paused, its output is read and this is used to update the game
state. This continues until the game reports that it is finished.

** Project structure

Functions for interacting with processes are found in the runtime
module. A game runner for an n-player game is found in the game-runner
module. The footsoldiers module provides an implementation of a game.
The example-bots directory contains starter implementions of bots in
various languages for the footsoldiers game.

** Running a game 

A game can be run by executing the following command in the
footsoldiers directory of the bot-match repo after pullling the docker
container for the runner (henrys1/bot-match in Docker Hub).

#+begin_src bash
docker run --name bot-match-runner --rm -v /var/run/docker.sock:/var/run/docker.sock -u root -v ${PWD}:/footsoldiers -v ${PWD}/../example-bots/java:/bot bot-runner --bot-dir-1 /bot --bot-dir-2 /bot --map-file-path /footsoldiers/game-map --config-file-path /footsoldiers/game-config.json
#+end_src

** License

The project is provided under the MIT license. See the LICENSE file
for details.
