[[https://github.com/HenryS1/bot-match/tree/master][https://github.com/HenryS1/bot-match/actions/workflows/ci.yaml/badge.svg]]

* Bot match

This project provides building blocks for a AI bot match runner. Bot
processes are run on the same machine as the runner. All bot processes
are started as the game launches and immediately paused. 

At the start of each bot's turn the bot process is resumed and given
its input for the turn. After the allocated turn time the bot process
is paused, its output is read and this is used to update the game
state.

This continues until the game reports that it is finished.

** Project structure

Functions for interacting with processes are found in the runtime
module. A game runner for an n-player game is found in the game-runner
module. The footsoldiers module provides an implementation of a game.
The example-bots directory contains starter implementions of bots in
various languages for the footsoldiers game.

** Platform

The project only runs on *nix systems because it uses os signals to
manage processes. It also requires the SBCL lisp compiler, because it
uses SBCL funcions for process management.

** License

The project is provided under the MIT license. See the LICENSE file
for details.
