/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BotTest {
    @Test void trueIsTrue() {
        assertTrue(true);
    }
}
