name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-18.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
        run: |
          wget https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh
          chmod +x ./install-for-ci.sh
          ./install-for-ci.sh

      - name: Install Rove
        run: ros install rove
      - name: Install qlot
        run: ros install qlot

      - name: Install dependencies
        run: |
          PATH="~/.roswell/bin:$PATH"
          qlot install

      - name: Build docker container
        run: |
          docker build . --tag bot-match/lisp-base

      - name: Run game runner tests      
        working-directory: ./game-runner
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove game-runner.asd

      - name: Run runtime tests
        working-directory: ./runtime
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove runtime.asd

      - name: Run footsoldiers tests
        working-directory: ./footsoldiers
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove footsoldiers.asd
