name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-18.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          load: true
          tags: bot-match/lisp-base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache      

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
        run: |
          wget https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh
          chmod +x ./install-for-ci.sh
          ./install-for-ci.sh

      - name: Install Rove
        run: ros install rove
      - name: Install qlot
        run: ros install qlot

      - name: Install dependencies
        run: |
          PATH="~/.roswell/bin:$PATH"
          qlot install

      - name: Run game runner tests      
        working-directory: ./game-runner
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove game-runner.asd

      - name: Run runtime tests
        working-directory: ./runtime
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove runtime.asd

      - name: Run footsoldiers tests
        working-directory: ./footsoldiers
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove footsoldiers.asd
