name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-18.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build docker container
        run: |
          docker build . --tag footsoldiers-runner

      - name: Run game runner tests      
        run: |
          docker run --entrypoint /home/footsoldiers/.roswell/bin/rove footsoldiers-runner game-runner/game-runner.asd

      - name: Run runtime tests
        run: |
          docker run --entrypoint /home/footsoldiers/.roswell/bin/rove footsoldiers-runner runtime/runtime.asd

      - name: Run footsoldiers tests
        run: |
          docker run --entrypoint /home/footsoldiers/.roswell/bin/rove footsoldiers-runner footsoldiers/footsoldiers.asd
