name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
        run: |
          wget https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh
          chmod +x ./install-for-ci.sh
          ./install-for-ci.sh
      - name: Install Rove
        run: ros install rove
      - name: Install qlot
        run: ros install qlot
      - name: Install dependencies
        run: |
          PATH="~/.roswell/bin:$PATH"
          qlot install
      - name: Run game runner tests      
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove game-runner/game-runner.asd
      - name: Run runtime tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove runtime/runtime.asd
      - name: Run footsoldiers tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove footsoldiers/footsoldiers.asd
