name: Publish docker image

on:
  push: 
    tags: 
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-21.04
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bot-match/footsoldiers-runner

      - name: Login into Github container registry
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
